#!/bin/bash
. ${TRAVIS_SUBMODULE}/config.sh

# Set debug mode
set -x
set -v

# Display post-failure environment
echo "Environment:"
env

# Dump logs of the current build
find "$ROOT_DIR/build" -name "*.log" | xargs cat

# End debug mode
set +v
set +x
