#!/bin/bash
set -ev

. ${TRAVIS_SUBMODULE}/${TRAVIS_OS_NAME}/install
. ${TRAVIS_SUBMODULE}/common/dependencies.sh

# Create layout.
SOURCE_DIR="$DEVEL_DIR/src"
INSTALL_DIR="$DEVEL_DIR/install"
rm -rf "$SOURCE_DIR" "$INSTALL_DIR"
mkdir -p "$SOURCE_DIR"
mkdir -p "$INSTALL_DIR"

. ${TRAVIS_SUBMODULE}/common/config.sh
