#!/bin/bash
set -ev

. ${TRAVIS_SUBMODULE}/${TRAVIS_OS_NAME}/install
. ${TRAVIS_SUBMODULE}/common/dependencies.sh

# Create layout.
DEVEL_DIR="$ROOT_DIR/_travis"
SOURCE_DIR="$DEVEL_DIR/src"
INSTALL_DIR="$DEVEL_DIR/install"
rm -rf "$SOURCE_DIR" "$INSTALL_DIR"
mkdir -p "$SOURCE_DIR"
mkdir -p "$INSTALL_DIR"

# Setup environment variables.
export LD_LIBRARY_PATH="$INSTALL_DIR/lib:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$INSTALL_DIR/lib/`dpkg-architecture -qDEB_BUILD_MULTIARCH`:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH="$INSTALL_DIR/lib/pkgconfig:$PKG_CONFIG_PATH"
export PKG_CONFIG_PATH="$INSTALL_DIR/lib/`dpkg-architecture -qDEB_BUILD_MULTIARCH`/pkgconfig:$PKG_CONFIG_PATH"
