#!/bin/bash
set -ev

. ${TRAVIS_SUBMODULE}/${TRAVIS_OS_NAME}/install
. ${TRAVIS_SUBMODULE}/common/dependencies.sh

# Create layout.
SOURCE_DIR="$DEVEL_DIR/src"
INSTALL_DIR="$DEVEL_DIR/install"
rm -rf "$SOURCE_DIR" "$INSTALL_DIR"
mkdir -p "$SOURCE_DIR"
mkdir -p "$INSTALL_DIR"

. ${TRAVIS_SUBMODULE}/config.sh

for package in ${EXTERNAL_DEPENDENCIES}; do
  install_${package}
done

for package in ${HPP_DEPENDENCIES}; do
  install_github_dependency humanoid-path-planner/${package} ${TRAVIS_BRANCH}
done
