#!/bin/bash
set -ev

. ${TRAVIS_SUBMODULE}/common/config.sh

cd ${ROOT_DIR}
[ ! -d "build" ] && mkdir -p "build"
cd "build"
cmake "$ROOT_DIR" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:STRING="$DEVEL_DIR/install"
make
make test
make install
make uninstall
