#!/bin/sh
set -ev

: ${CMAKE_CXX_FLAGS="-Wno-conversion -Wno-variadic-macros -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-c99-extensions -Wno-redeclared-class-member -Wno-unused-parameter -Wno-overloaded-virtual"}
: ${CMAKE_ARGS="-Wno-dev"}
export CMAKE_ARGS CMAKE_CXX_FLAGS

. ${TRAVIS_SUBMODULE}/common/functions.sh

# Some functions
install_libccd()
{
  brew install libccd
}

install_doxygen()
{
  brew install doxygen
}

silent_brew ()
{
  brew $@ > /dev/null
}

BREW=silent_brew

${BREW} tap homebrew/science
${BREW} install cmake tinyxml pkg-config

if [ "x${BREW_PACKAGES}" != "x" ]; then
  ${BREW} install ${BREW_PACKAGES}
fi
